project_name: Paperboy

builds:
  - binary: paperboy
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
    tags: ['{{ if .Env.BUILD_WITH_UI }}withUI{{ else }}noUI{{ end }}']
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - format: tar.gz
    wrap_in_directory: false
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true

release:
  draft: true
