name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Install Node
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: 'ui/yarn.lock'
          node-version-file: 'ui/package.json'
          cache: 'yarn'
      -
        name: Build UI with Ember
        working-directory: ./ui
        run: |
          yarn install
          yarn run build
      -
        name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_WITH_UI: true
